module Config
  KAFKA_HOST = ENV['KAFKA_PORT_9092_TCP_ADDR']
  KAFKA_PORT = ENV['KAFKA_PORT_9092_TCP_PORT']
  ZK_HOST = ENV['ZK_PORT_2181_TCP_ADDR']
  ZK_PORT = ENV['ZK_PORT_2181_TCP_PORT']
  PRO_ID = 'pro_id'
  CONS_ID = 'cons_id'
  REQUESTS_QUEUE = 'reqs'
  SOL_TOPIC = 'sol'
end
